/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.util.List;
import Model.ChitietHoadonTong;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PRINCE D. TOAD
 */
public class ChitietKhunggioFrm extends javax.swing.JFrame {

    private DefaultTableModel defaultTableModel;

    /**
     * Creates new form ChitietKhunggioFrm
     */
    public ChitietKhunggioFrm(int i, List<ChitietHoadonTong> listHDTong) {
        initComponents();

        defaultTableModel = (DefaultTableModel) tblChitiet.getModel();
        tblChitiet.setModel(defaultTableModel);

        for (ChitietHoadonTong hdTong : listHDTong) {
            // neu van be hon 23h
            if (i < 23) {
                    // so sanh khung gio tu i -> i+1
                // neu gio bat dau < gio ket thuc thi hat trong ngay
                if (hdTong.getGioBatdau().getHours()
                        <= hdTong.getGioKetthuc().getHours()) {
                    if (hdTong.getGioBatdau().getHours() <= i
                            && hdTong.getGioKetthuc().getHours() >= i + 1) {
                        defaultTableModel.addRow(new Object[]{
                            hdTong.getMaHoadon(),
                            hdTong.getTenKH(),
                            hdTong.getNgayTaoHD(),
                            hdTong.getGioBatdau() + " -> " + hdTong.getGioKetthuc(),
                            hdTong.getTongtien()
                        });
                    }
                } else {
                    if (hdTong.getGioBatdau().getHours() <= i
                            && hdTong.getGioKetthuc().getHours() <= i + 1) {
                        defaultTableModel.addRow(new Object[]{
                            hdTong.getMaHoadon(),
                            hdTong.getTenKH(),
                            hdTong.getNgayTaoHD(),
                            hdTong.getGioBatdau() + " -> " + hdTong.getGioKetthuc(),
                            hdTong.getTongtien()
                        });
                    } else if (hdTong.getGioBatdau().getHours() >= i
                            && hdTong.getGioKetthuc().getHours() >= i + 1) {
                        defaultTableModel.addRow(new Object[]{
                            hdTong.getMaHoadon(),
                            hdTong.getTenKH(),
                            hdTong.getNgayTaoHD(),
                            hdTong.getGioBatdau() + " -> " + hdTong.getGioKetthuc(),
                            hdTong.getTongtien()
                        });
                    }
                }

            } else {
                // tu 23h -> 0h
                if (hdTong.getGioBatdau().getHours()
                        <= hdTong.getGioKetthuc().getHours()) {
                    if (hdTong.getGioBatdau().getHours() <= i
                            && hdTong.getGioKetthuc().getHours() == 0) {
                        defaultTableModel.addRow(new Object[]{
                            hdTong.getMaHoadon(),
                            hdTong.getTenKH(),
                            hdTong.getNgayTaoHD(),
                            hdTong.getGioBatdau() + " -> " + hdTong.getGioKetthuc(),
                            hdTong.getTongtien()
                        });
                    }
                } else {
                    if (hdTong.getGioBatdau().getHours() <= i
                            && hdTong.getGioKetthuc().getHours() >= 0) {
                        defaultTableModel.addRow(new Object[]{
                            hdTong.getMaHoadon(),
                            hdTong.getTenKH(),
                            hdTong.getNgayTaoHD(),
                            hdTong.getGioBatdau() + " -> " + hdTong.getGioKetthuc(),
                            hdTong.getTongtien()
                        });
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblChitiet = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblChitiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Tên khách hàng", "Ngày thanh toán", "Giờ hát", "Tổng tiền"
            }
        ));
        jScrollPane1.setViewportView(tblChitiet);

        jButton1.setText("Quay lại");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(258, 258, 258))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton1)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblChitiet;
    // End of variables declaration//GEN-END:variables
}
